import { StyleSheet } from "react-native-unistyles";

export const styles = StyleSheet.create((theme) => ({
  avatar: {
    backgroundColor: theme.colors.imagePlaceholder,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.full,
    borderWidth: 1,
    height: theme.size.avatar,
    width: theme.size.avatar,
  },
  card: {
    backgroundColor: theme.colors.surfaceRaised,
    borderColor: theme.colors.accentSoft,
    borderCurve: "continuous",
    borderRadius: theme.radius.lg,
    borderWidth: theme.border.default,
    boxShadow: theme.shadow.card,
    gap: theme.space.md,
    padding: theme.space.md,
  },
  details: { flex: 1 },
  credit: { flex: 1 },
  heartCircle: {
    backgroundColor: theme.colors.accentSecondarySoft,
    borderRadius: theme.radius.full,
    boxShadow: theme.shadow.floating,
    padding: theme.space.lg,
  },
  heartOverlay: {
    alignItems: "center",
    bottom: 0,
    justifyContent: "center",
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  image: { aspectRatio: 4 / 5, width: "100%" },
  imageContainer: {
    backgroundColor: theme.colors.imagePlaceholder,
    borderCurve: "continuous",
    borderRadius: theme.radius.md,
    overflow: "hidden",
  },
  likeButton: {
    backgroundColor: theme.colors.surfaceRaised,
    borderRadius: theme.radius.full,
    bottom: theme.space.sm,
    boxShadow: theme.shadow.floating,
    padding: theme.space.sm,
    position: "absolute",
    right: theme.space.sm,
  },
  location: { alignItems: "center", flexDirection: "row", gap: theme.space.xxs },
  mediaFooter: {
    alignItems: "center",
    flexDirection: "row",
    gap: theme.space.sm,
  },
  profile: { alignItems: "center", flexDirection: "row", gap: theme.space.sm },
  saveButton: {
    alignItems: "center",
    backgroundColor: theme.colors.surfaceSubtle,
    borderColor: theme.colors.border,
    borderCurve: "continuous",
    borderRadius: theme.radius.full,
    borderWidth: theme.border.default,
    flexDirection: "row",
    gap: theme.space.xxs,
    justifyContent: "center",
    minHeight: theme.size.compactTouch,
    paddingHorizontal: theme.space.sm,
  },
  saveButtonDisabled: { opacity: 0.72 },
  saveButtonLabel: {
    color: theme.colors.textSecondary,
    fontWeight: "700",
  },
  saveButtonPressed: { opacity: 0.82 },
  storyDot: {
    backgroundColor: theme.colors.accentSecondary,
    borderRadius: theme.radius.full,
    height: theme.space.xs,
    width: theme.space.xs,
  },
  storyLabel: { color: theme.colors.accentSecondary },
  storyLine: { alignItems: "center", flexDirection: "row", gap: theme.space.xxs },
}));
