import { StyleSheet } from "react-native-unistyles";

export const styles = StyleSheet.create((theme) => ({
  centered: { flex: 1, justifyContent: "center", paddingHorizontal: theme.layout.screenGutter },
  content: { paddingBottom: theme.space.xxxl, paddingHorizontal: theme.layout.screenGutter },
  footer: { alignItems: "center", paddingVertical: theme.space.xl },
  header: { gap: theme.space.xl, paddingBottom: theme.space.xl, paddingTop: theme.space.lg },
  list: { backgroundColor: theme.colors.background, flex: 1 },
  loadingFooter: { paddingTop: theme.space.sm },
  searchButton: {
    alignItems: "center",
    backgroundColor: theme.colors.accent,
    borderCurve: "continuous",
    borderRadius: theme.radius.sm,
    justifyContent: "center",
    minHeight: theme.size.compactTouch,
    paddingHorizontal: theme.space.md,
  },
  searchButtonDisabled: { backgroundColor: theme.colors.disabled },
  searchButtonPressed: { backgroundColor: theme.colors.accentPressed },
  searchButtonText: { color: theme.colors.onAccent, fontWeight: "700" },
  searchButtonTextDisabled: { color: theme.colors.textTertiary },
  searchCard: {
    alignItems: "center",
    backgroundColor: theme.colors.surfaceRaised,
    borderColor: theme.colors.border,
    borderCurve: "continuous",
    borderRadius: theme.radius.lg,
    borderWidth: theme.border.default,
    flexDirection: "row",
    gap: theme.space.sm,
    padding: theme.space.xs,
  },
  searchInput: {
    color: theme.colors.text,
    flex: 1,
    fontSize: theme.typography.body.fontSize,
    minHeight: theme.size.compactTouch,
    paddingVertical: theme.space.none,
  },
  searchInputRow: {
    alignItems: "center",
    backgroundColor: theme.colors.inputBackground,
    borderColor: theme.colors.inputBorder,
    borderCurve: "continuous",
    borderRadius: theme.radius.md,
    borderWidth: theme.border.default,
    flex: 1,
    flexDirection: "row",
    gap: theme.space.xs,
    minHeight: theme.size.compactTouch,
    paddingHorizontal: theme.space.sm,
  },
  separator: { height: theme.space.lg },
}));
