import { StyleSheet } from "react-native-unistyles";

export const styles = StyleSheet.create((theme, rt) => ({
  camera: { flex: 1 },
  cameraOverlay: {
    bottom: rt.insets.bottom + theme.space.md,
    justifyContent: "space-between",
    left: 0,
    paddingHorizontal: theme.layout.screenGutter,
    position: "absolute",
    right: 0,
    top: rt.insets.top + theme.space.md,
  },
  captureRow: { alignItems: "center", flexDirection: "row", gap: theme.space.xl, justifyContent: "center" },
  checking: {
    alignItems: "center",
    backgroundColor: theme.colors.cameraBackground,
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: theme.space.xl,
  },
  draftActions: { gap: theme.space.md },
  draftImage: { bottom: 0, left: 0, position: "absolute", right: 0, top: 0 },
  draftOverlay: {
    flex: 1,
    justifyContent: "space-between",
    paddingBottom: rt.insets.bottom + theme.space.md,
    paddingHorizontal: theme.layout.screenGutter,
    paddingTop: rt.insets.top + theme.space.lg,
  },
  draftRoot: { flex: 1 },
  draftRow: { flexDirection: "row", gap: theme.space.sm, justifyContent: "space-between" },
  message: {
    backgroundColor: theme.colors.cameraScrim,
    borderCurve: "continuous",
    borderRadius: theme.radius.md,
    maxWidth: theme.layout.cameraMessageMaxWidth,
    padding: theme.space.sm,
  },
  permission: { backgroundColor: theme.colors.background, flex: 1, justifyContent: "center", paddingHorizontal: theme.layout.screenGutter },
  root: { backgroundColor: theme.colors.cameraBackground, flex: 1 },
  shutter: {
    alignItems: "center",
    backgroundColor: theme.colors.cameraScrim,
    borderColor: theme.colors.accentSecondary,
    borderRadius: theme.radius.full,
    borderWidth: theme.border.shutter,
    justifyContent: "center",
    padding: theme.space.md,
  },
  spacer: { width: theme.size.touch },
  topControl: { alignItems: "flex-start" },
  tutorial: { alignItems: "center", gap: theme.space.lg },
  tutorialText: { maxWidth: theme.layout.tutorialMaxWidth },
}));
