import { StyleSheet } from "react-native-unistyles";

export const styles = StyleSheet.create((theme, rt) => ({
  camera: { flex: 1 },
  cameraOverlay: {
    bottom: rt.insets.bottom + 18,
    justifyContent: "space-between",
    left: 0,
    paddingHorizontal: 20,
    position: "absolute",
    right: 0,
    top: rt.insets.top + 18,
  },
  captureRow: { alignItems: "center", flexDirection: "row", gap: 24, justifyContent: "center" },
  checking: {
    alignItems: "center",
    backgroundColor: "#000000",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  draftActions: { gap: 16 },
  draftImage: { bottom: 0, left: 0, position: "absolute", right: 0, top: 0 },
  draftOverlay: {
    flex: 1,
    justifyContent: "space-between",
    paddingBottom: rt.insets.bottom + 16,
    paddingHorizontal: 20,
    paddingTop: rt.insets.top + 20,
  },
  draftRoot: { flex: 1 },
  draftRow: { flexDirection: "row", gap: 12, justifyContent: "space-between" },
  inverseText: { color: theme.colors.inverse },
  lightButton: { backgroundColor: theme.colors.inverse, flex: 1, paddingVertical: 12 },
  message: {
    backgroundColor: theme.colors.overlayStrong,
    borderCurve: "continuous",
    borderRadius: 24,
    maxWidth: 250,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  permission: { backgroundColor: theme.colors.canvas, flex: 1, justifyContent: "center", paddingHorizontal: 20 },
  root: { backgroundColor: "#000000", flex: 1 },
  shutter: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderColor: theme.colors.inverse,
    borderRadius: 999,
    borderWidth: 4,
    justifyContent: "center",
    padding: 16,
  },
  spacer: { width: 52 },
  topControl: { alignItems: "flex-start" },
  transparentButton: { backgroundColor: theme.colors.overlay },
  tutorial: { alignItems: "center", gap: 20 },
  tutorialText: { maxWidth: 320 },
}));
