import { StyleSheet } from "react-native-unistyles";

export const styles = StyleSheet.create((theme) => ({
  action: {
    backgroundColor: theme.colors.canvas,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  actionRow: { alignItems: "center", flexDirection: "row", gap: 8 },
  actions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  card: {
    backgroundColor: theme.colors.surface,
    borderCurve: "continuous",
    borderRadius: 28,
    gap: 16,
    padding: 16,
  },
  centered: { flex: 1, justifyContent: "center", paddingHorizontal: 20 },
  content: { paddingBottom: 40, paddingHorizontal: 20 },
  header: { gap: 24, paddingBottom: 20, paddingHorizontal: 20, paddingTop: 24 },
  image: {
    backgroundColor: theme.colors.canvas,
    borderCurve: "continuous",
    borderRadius: 20,
    height: 96,
    width: 96,
  },
  info: { flex: 1, gap: 12, justifyContent: "space-between" },
  intro: { gap: 4 },
  list: { backgroundColor: theme.colors.canvas, flex: 1 },
  photoRow: { flexDirection: "row", gap: 16 },
  profileCard: {
    backgroundColor: theme.colors.surface,
    borderCurve: "continuous",
    borderRadius: 32,
    gap: 20,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  profileImage: {
    backgroundColor: theme.colors.canvas,
    borderRadius: 999,
    height: 96,
    width: 96,
  },
  profileInfo: { flex: 1, gap: 4 },
  profileRow: { alignItems: "center", flexDirection: "row", gap: 16 },
  section: { gap: 4 },
  separator: { height: 16 },
  stat: {
    backgroundColor: theme.colors.canvas,
    borderCurve: "continuous",
    borderRadius: 24,
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  statRow: { flexDirection: "row", gap: 12, justifyContent: "space-between" },
  statValue: { marginTop: 12 },
}));
