import { StyleSheet } from "react-native-unistyles";

export const styles = StyleSheet.create((theme) => ({
  accountCopy: { flex: 1, gap: theme.space.xxs, minWidth: 0 },
  accountPanel: {
    alignItems: "center",
    backgroundColor: theme.colors.surfaceRaised,
    borderColor: theme.colors.border,
    borderCurve: "continuous",
    borderRadius: theme.radius.md,
    borderWidth: theme.border.default,
    flexDirection: "row",
    gap: theme.space.sm,
    justifyContent: "space-between",
    minWidth: 0,
    padding: theme.space.md,
  },
  actions: { alignItems: "center", flexDirection: "row", flexWrap: "wrap", gap: theme.space.xs },
  card: {
    backgroundColor: theme.colors.surfaceRaised,
    borderColor: theme.colors.border,
    borderCurve: "continuous",
    borderRadius: theme.radius.lg,
    borderWidth: theme.border.default,
    gap: theme.space.md,
    padding: theme.space.md,
  },
  copyStack: { gap: theme.space.xxs },
  centered: { flex: 1, justifyContent: "center", paddingHorizontal: theme.layout.screenGutter },
  content: { paddingBottom: theme.space.xxxl, paddingHorizontal: theme.layout.screenGutter },
  header: { gap: theme.space.xl, paddingBottom: theme.space.lg, paddingTop: theme.space.lg },
  image: {
    backgroundColor: theme.colors.imagePlaceholder,
    borderCurve: "continuous",
    borderRadius: theme.radius.md,
    height: theme.size.galleryThumbnail,
    width: theme.size.galleryThumbnail,
  },
  info: { flex: 1, gap: theme.space.sm, justifyContent: "space-between", minWidth: 0 },
  likedActions: {
    alignItems: "stretch",
    flexDirection: "column",
    gap: theme.space.xs,
  },
  likedCard: (columnIndex: number) => ({
    backgroundColor: theme.colors.surfaceRaised,
    borderColor: theme.colors.border,
    borderCurve: "continuous",
    borderRadius: theme.radius.lg,
    borderWidth: theme.border.default,
    flex: 1,
    gap: theme.space.sm,
    marginLeft: columnIndex === 0 ? 0 : theme.space.xs / 2,
    marginRight: columnIndex === 0 ? theme.space.xs / 2 : 0,
    overflow: "hidden",
    padding: theme.space.sm,
  }),
  likedCardCopy: { gap: theme.space.xs },
  likedGridRow: { flexDirection: "row" },
  likedGridSpacer: { flex: 1, marginLeft: theme.space.xs / 2 },
  likedImage: {
    aspectRatio: 1,
    backgroundColor: theme.colors.imagePlaceholder,
    width: "100%",
  },
  likedImageFrame: {
    backgroundColor: theme.colors.imagePlaceholder,
    borderCurve: "continuous",
    borderRadius: theme.radius.md,
    overflow: "hidden",
  },
  list: { backgroundColor: theme.colors.background, flex: 1 },
  photoRow: { flexDirection: "row", gap: theme.space.md },
  profileCard: {
    backgroundColor: theme.colors.surfaceBrand,
    borderColor: theme.colors.border,
    borderCurve: "continuous",
    borderRadius: theme.radius.lg,
    borderWidth: theme.border.default,
    gap: theme.space.lg,
    padding: theme.space.lg,
  },
  profileImage: {
    backgroundColor: theme.colors.imagePlaceholder,
    borderRadius: theme.radius.full,
    height: theme.size.profileAvatar,
    width: theme.size.profileAvatar,
  },
  profileInfo: { flex: 1, gap: theme.space.xxs, minWidth: 0 },
  profileRow: { alignItems: "center", flexDirection: "row", gap: theme.space.md },
  separator: { height: theme.space.sm },
  segmentedControl: {
    backgroundColor: theme.colors.surfaceSubtle,
    borderColor: theme.colors.border,
    borderCurve: "continuous",
    borderRadius: theme.radius.full,
    borderWidth: theme.border.default,
    flexDirection: "row",
    gap: theme.space.xxs,
    padding: theme.space.xxs,
  },
  segmentedOption: (selected: boolean) => ({
    alignItems: "center",
    backgroundColor: selected ? theme.colors.surfaceRaised : "transparent",
    borderCurve: "continuous",
    borderRadius: theme.radius.full,
    flex: 1,
    justifyContent: "center",
    minHeight: theme.size.compactTouch,
    paddingHorizontal: theme.space.sm,
  }),
  segmentedOptionContent: {
    alignItems: "center",
    flexDirection: "row",
    gap: theme.space.xs,
  },
  segmentedOptionPressed: { opacity: 0.82 },
  segmentedOptionText: (selected: boolean) => ({
    color: selected ? theme.colors.text : theme.colors.textSecondary,
    fontWeight: selected ? "800" : "700",
  }),
  segmentedBadge: (selected: boolean) => ({
    backgroundColor: selected ? theme.colors.accentSoft : theme.colors.surfaceRaised,
    borderCurve: "continuous",
    borderRadius: theme.radius.full,
    color: selected ? theme.colors.accent : theme.colors.textSecondary,
    fontWeight: "800",
    minWidth: theme.size.iconLg,
    overflow: "hidden",
    paddingHorizontal: theme.space.xs,
    textAlign: "center",
  }),
  restoreCopy: { flex: 1, gap: theme.space.xxs, minWidth: 0 },
  restoreNotice: {
    alignItems: "center",
    backgroundColor: theme.colors.successSoft,
    borderColor: theme.colors.success,
    borderCurve: "continuous",
    borderRadius: theme.radius.md,
    borderWidth: theme.border.default,
    flexDirection: "row",
    gap: theme.space.sm,
    padding: theme.space.sm,
  },
}));
