import { StyleSheet } from "react-native-unistyles";

export const styles = StyleSheet.create((theme, rt) => ({
  bottomBar: {
    alignItems: "center",
    backgroundColor: theme.colors.cameraScrim,
    borderCurve: "continuous",
    borderRadius: theme.radius.lg,
    bottom: rt.insets.bottom + theme.space.md,
    flexDirection: "row",
    gap: theme.space.md,
    left: theme.layout.screenGutter,
    padding: theme.space.sm,
    position: "absolute",
    right: theme.layout.screenGutter,
  },
  disabled: { opacity: 0.72 },
  iconButton: {
    alignItems: "center",
    backgroundColor: theme.colors.cameraScrim,
    borderRadius: theme.radius.full,
    justifyContent: "center",
    minHeight: theme.size.compactTouch,
    minWidth: theme.size.compactTouch,
  },
  image: { height: "100%", width: "100%" },
  page: (width: number) => ({
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingBottom: rt.insets.bottom + theme.space.xxxl,
    paddingTop: rt.insets.top + theme.space.xxxl,
    width,
  }),
  pressed: { opacity: 0.82 },
  root: {
    backgroundColor: theme.colors.cameraBackground,
    flex: 1,
  },
  saveButton: {
    alignItems: "center",
    backgroundColor: theme.colors.surfaceRaised,
    borderCurve: "continuous",
    borderRadius: theme.radius.full,
    flexDirection: "row",
    gap: theme.space.xs,
    justifyContent: "center",
    minHeight: theme.size.compactTouch,
    paddingHorizontal: theme.space.md,
  },
  saveButtonLabel: {
    color: theme.colors.text,
    fontWeight: "700",
  },
  topBar: {
    alignItems: "flex-end",
    left: theme.layout.screenGutter,
    position: "absolute",
    right: theme.layout.screenGutter,
    top: rt.insets.top + theme.space.md,
  },
  viewerDetails: {
    flex: 1,
    gap: theme.space.xxs,
    minWidth: 0,
  },
  viewerSubtitle: { color: theme.colors.textInverse, opacity: 0.76 },
  viewerTitle: { color: theme.colors.textInverse },
}));
