import { StyleSheet } from "react-native-unistyles";

export const styles = StyleSheet.create((theme, rt) => ({
  background: { bottom: 0, left: 0, position: "absolute", right: 0, top: 0 },
  card: {
    alignSelf: "center",
    backgroundColor: "rgba(61, 40, 25, 0.76)",
    borderCurve: "continuous",
    borderRadius: theme.radius.lg,
    gap: theme.space.lg,
    maxWidth: theme.layout.welcomeCardMaxWidth,
    padding: theme.space.xl,
    width: rt.screen.width - theme.space.xl,
  },
  content: {
    flex: 1,
    justifyContent: "flex-end",
    paddingBottom: rt.insets.bottom + theme.space.md,
    paddingHorizontal: theme.space.md,
    paddingTop: rt.insets.top,
  },
  brandRow: { alignItems: "center", flexDirection: "row", gap: theme.space.sm },
  copy: { gap: theme.space.sm },
  errorMessage: { color: theme.colors.onWarningSoft },
  errorPanel: {
    backgroundColor: theme.colors.warningSoft,
    borderColor: theme.colors.warning,
    borderCurve: "continuous",
    borderRadius: theme.radius.md,
    borderWidth: theme.border.default,
    gap: theme.space.xxs,
    padding: theme.space.sm,
  },
  errorTitle: { color: theme.colors.onWarningSoft },
  icon: { borderRadius: theme.radius.md, height: theme.size.touch, overflow: "hidden", width: theme.size.touch },
  iconImage: { height: "100%", width: "100%" },
  root: { backgroundColor: theme.colors.background, flex: 1 },
  signInButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.borderStrong,
    borderRadius: theme.radius.md,
    borderWidth: theme.border.default,
    flexDirection: "row",
    gap: theme.space.xs,
    minHeight: theme.size.touch,
    paddingHorizontal: theme.space.md,
  },
  signInButtonDisabled: { opacity: 0.7 },
  signInButtonPressed: { backgroundColor: theme.colors.surfacePressed },
  signInLabel: {
    color: theme.colors.text,
    fontSize: theme.typography.title.fontSize,
    fontWeight: "600",
  },
  title: { maxWidth: 384 },
}));
